// src/words.js
const WORDS = [
  "SAGAZ", "NOBRE", "AMIGO", "TERMO", "PLENA", "MUTIO", "VORAZ", "FAZER", "SABER", "CASAL",
  "IDEIA", "PODER", "MUNDO", "TEMPO", "VALER", "CRIAR", "PEDIR", "FUGIR", "LOGICA", "VIVAZ",
  "ROSTO", "PORTA", "MENTE", "CORPO", "FALHA", "FORTE", "VAPOR", "VENDER", "OUVIR", "LINDA",
  "CHAVE", "BRAVO", "VISTA", "ATIVO", "LETRA", "NOITE", "SABOR", "LEVAR", "FORMA", "MANHA",
  "PONTO", "TERRA", "LUGAR", "JOVEM", "CAUSA", "PRECO", "GRUPO", "PLANO", "VIVER", "PESSO",
  "ASTRAL", "SUTIL", "CUIDAR", "GUSTO", "LANCE", "MOSCA", "BRIGA", "TRENO", "FORNO", "FESTA",
  "NATIVO", "SALTO", "MARCO", "UNIAO", "LINHA", "FOGO", "AGUA", "VENTO", "PEDRA", "CORRE",
  "ANJO", "BANDA", "CANTO", "DANCA", "GANHO", "HONRA", "JUSTO", "LIVRO", "MAPA", "NAVIO",
  "OURO", "PRATA", "QUASE", "RADIO", "SANTO", "TOURO", "URSO", "VASO", "ZEBRA", "BRUXO",
  "CARRO", "DENTE", "FERRO", "GATO", "HARPA", "IRMAO", "JANELA", "LEAO", "MACA", "NINHO"
];

module.exports = { WORDS };